name: Build .NET component and Docker push
on:
  push:
    paths-ignore:
      - "docs/**"
      - "*.md"
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:
  
jobs:
  dotnet-ci:
    uses: gianfragolo/backstage-metadata/.github/workflows/dotnet-build-and-push.yml@main
    secrets: inherit
    with:
      component: acme-landing-ui
      repoOwner: gianfragolo
      repoName: acme-landing-ui
